local ServerEventCode = Define("ServerEventCode")

ServerEventCode.CODE_CLIENT_EXIT = "CODE_CLIENT_EXIT"
ServerEventCode.CODE_CLIENT_OFFLINE = "CODE_CLIENT_OFFLINE"
ServerEventCode.CODE_CLIENT_NICKNAME_SET = "CODE_CLIENT_NICKNAME_SET"
ServerEventCode.CODE_CLIENT_HEAD_BEAT = "CODE_CLIENT_HEAD_BEAT"
ServerEventCode.CODE_ROOM_CREATE = "CODE_ROOM_CREATE"
ServerEventCode.CODE_ROOM_CREATE_PVE = "CODE_ROOM_CREATE_PVE"
ServerEventCode.CODE_GET_ROOMS = "CODE_GET_ROOMS"
ServerEventCode.CODE_ROOM_JOIN = "CODE_ROOM_JOIN"
ServerEventCode.CODE_GAME_STARTING = "CODE_GAME_STARTING"
ServerEventCode.CODE_GAME_LANDLORD_ELECT = "CODE_GAME_LANDLORD_ELECT"
ServerEventCode.CODE_GAME_POKER_PLAY = "CODE_GAME_POKER_PLAY"
ServerEventCode.CODE_GAME_POKER_PLAY_REDIRECT = "CODE_GAME_POKER_PLAY_REDIRECT"
ServerEventCode.CODE_GAME_POKER_PLAY_PASS = "CODE_GAME_POKER_PLAY_PASS"
ServerEventCode.CODE_GAME_WATCH = "CODE_GAME_WATCH"
ServerEventCode.CODE_GAME_WATCH_EXIT = "CODE_GAME_WATCH_EXIT"

return ServerEventCode
